# Site settings
title: TADP
header-img: img/home-bg.jpg
description: "Pagina de TADP. Electiva de 3er anio de la UTN FRBA"
baseurl: ""
url: "http://tadp-utn-frba.github.io"
github_username: "tadp-utn-frba"
disqus:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: blog/page:num
exclude: ["vendor","less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: ['jekyll-paginate', 'rouge']
